baseURL = "http://oleh.pro"
languageCode = "en-us"
title = "Portfolio Oleh Akimenkov"
theme = "slate"

publishDir = "docs"

[ params ]
BackgroundImages = [
  "bg/b1920-000.jpg",
  "bg/b1920-001.jpg",
  "bg/b1920-002.jpg", 
  "bg/b1920-003.jpg",
  "bg/b1920-004.jpg"
]
Favicon = "favicon.ico"
BackgroundStyle = "radial-gradient(ellipse farthest-side at center top, #FCFCFC 0%, #657383 100%)"
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "favorites"
tag = "favorite"
icon = "star"

[[ params.nav ]]
name = "search"
tag = "search"
icon = "search"

[[ params.nav ]]
name = "shopping"
tag = "shopping"
icon = "shopping-basket"

[[ params.nav ]]
name = "music"
tag = "music"
icon = "headphones"

[[ params.nav ]]
name = "video"
tag = "video"
icon = "video-camera"